# @file Zsh Configuration
# @author Quinn Smith
# @date January 11th, 2020

#
# Basic ZSH Setup
#

# Set glob to be case insensitive
setopt NO_CASE_GLOB

# Auto CD so forgetting cd is not a big deal
setopt AUTO_CD

# Enable command history for zsh
setopt EXTENDED_HISTORY
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
SAVEHIST=5000
HISTSIZE=2000

# Enable zsh correction
setopt CORRECT
setopt CORRECT_ALL

# Enable better tab completion
autoload -U compinit 
zstyle ":completion:*" menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# 
# Aliases & Shortcuts
#

# Alias for a nice ls
local LS="ls --color"
alias ls="$LS"
alias ll="$LS -al"

# Alias for clear
alias cls="clear"

# Stuff for remote work at school
function ssh2ug() {
    local UG_MACHINE_NUMBER="169"
    if [[ -n $1 ]]; then
        UG_MACHINE_NUMBER=$1
    fi 
    ssh smithqu1@ug$UG_MACHINE_NUMBER.eecg.utoronto.ca
}

function ssh2ecf() {
    ssh smithqu1@remote.ecf.utoronto.ca
}

#
# Configure the prompt
#

# TODO: make this better
setopt PROMPT_SUBST 

# Assume we have colors available. This isn't the 1990's.
autoload colors && colors

# Load VCS Info for querying git
autoload vcs_info && vcs_info
zstyle ':vcs_info:*' enable git

precmd() { vcs_info }

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:*'    formats "%b─%m%u%c" 


# The purposes of the following functions are obvious
function get_time() {
    echo "%T"
}
function get_pwd() {
    echo "%~"
}
function get_user() {
    echo "%n"
}

function get_host() {
    echo "%m"
}

function get_prompt() {
    echo "%{$fg[cyan]%}[$(get_time)] %{$fg[yellow]%}$(get_user)@$(get_host): %{$fg[green]%}$(get_pwd) %{$reset_color%}"
}

PROMPT='$(get_prompt)'
export TERM=xterm-256color
