#!/bin/bash
# @file Query wifi info. Will be extended to also provide wired network info.
# @author Quinn Smith
# @date April 11th, 2020
# @dependencies date, font-awesome icon support

DATE_SYM='\uf073'
DATE_TIME=$( date +"%a %Y-%m-%d %H:%M %Z")
echo -e "$DATE_SYM $DATE_TIME"
