#!/bin/sh

sxhkd &
killall polybar
polybar -config .config/bspwm/polybar/config quinn & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config focus_follows_pointer true
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding 2

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale /home/quinn/.xmonad/wallpapers/firewatch.png
