#!/bin/bash

ECHO_STR=""
if [ -e /sys/class/power_supply/BAT0 ]; then
    BATTERY_STATS=$(acpi);
    BAT_STATUS=$(echo $BATTERY_STATS | awk '{print $3}' | tr -d ',') 
    BAT_PERCENTAGE=$(echo $BATTERY_STATS | grep -o "[[:digit:]]*%");

    if [ $BAT_STATUS = "Discharging" ]; then
        ECHO_STR="$BAT_PERCENTAGE"
    else
        ECHO_STR="$BAT_PERCENTAGE"
    fi
else
    ECHO_STR="N/A"
fi

echo $ECHO_STR

    
