#!/bin/bash

BAT_SYM='\uf241'
PLUG_SYM='\uf1e6'

ECHO_STR=""
if [ -e /sys/class/power_supply/BAT0 ]; then
    BATTERY_STATS=$(acpi);
    CHARGE_STATUS=$(echo $BATTERY_STATS | awk '{print $3}' | tr -d ',') 
    BAT_PERCENTAGE=$(echo $BATTERY_STATS | grep -o "[[:digit:]]*%");
    if [ $CHARGE_STATUS = "Discharging" ]; then
        ECHO_STR="$BAT_SYM $BAT_PERCENTAGE"
    else
        ECHO_STR="$PLUG_SYM $BAT_PERCENTAGE"
    fi
else
    ECHO_STR="$PLUG_SYM"
fi

echo -e $ECHO_STR

    
