#! /bin/bash

SOUND_ON=$(amixer sget Master | awk -F "[][]" '/dB/ {print $6}')
VOLUME=$(expr $(amixer sget Master | awk -F "[][]" '/dB/ {print $2+0}'))

if [ $SOUND_ON = "on" ]; then

    VOLUME_SYM=""
    if [ $VOLUME -eq 0 ]; then
        VOLUME_SYM='\uf026'
    elif [ $VOLUME -lt 50 ]; then
        VOLUME_SYM='\uf027'
    else
        VOLUME_SYM='\uf028'
    fi
    echo -e "$VOLUME_SYM $VOLUME%"
else
    echo -e "MUTE $VOLUME%"
fi
