#! /bin/bash

SOUND_ON=$(amixer sget Master | awk -F "[][]" '/dB/ {print $6}')
VOLUME=$(expr $(amixer sget Master | awk -F "[][]" '/dB/ {print $2+0}'))
VOLUME_SYM=""
VOLUME_VAL=""

if [ $VOLUME -eq 0 ]; then
    VOLUME_SYM='\uf026'
elif [ $VOLUME -lt 50 ]; then
    VOLUME_SYM='\uf027'
else
    VOLUME_SYM='\uf028'
fi

VOLUME_VAL="$VOLUME%"
if [ $SOUND_ON = "off" ]; then
    VOLUME_VAL="MUTE"
fi

echo -e "$VOLUME_SYM $VOLUME_VAL"
