#!/bin/bash
# @file Query wifi info. Will be extended to also provide wired network info.
# @author Quinn Smith
# @date April 11th, 2020
# @dependencies awk, grep, iwconfig, font-awesome icon support

if [ -e /proc/net/wireless ]; then
    WIRELESS_DEVICE="wlp2s0"
    
    # Wireless strength is given as a fraction turn it into a number from 0-100 
    WIRELESS_STRENGTH_FRACTION=$( iwconfig $WIRELESS_DEVICE | grep -o "Link Quality=[[:digit:]]*/[[:digit:]]*" | awk -F= '{print $2}');
    WIRELESS_NUMERATOR=$(echo $WIRELESS_STRENGTH_FRACTION | awk -F/ '{print $1}');
    WIRELESS_DENOMINATOR=$(echo $WIRELESS_STRENGTH_FRACTION | awk -F/ '{print $2}');
    WIRELESS_STRENGTH=$(awk "BEGIN{ print (int(($WIRELESS_NUMERATOR/$WIRELESS_DENOMINATOR)*100));}");

    WIRELESS_SYM='\uf1eb' 

    WIRELESS_NAME=$(iwconfig $WIRELESS_DEVICE | grep ESSID | awk -F: '{print $2}' | grep -o "\"\S*\""); 
    echo -e "$WIRELESS_SYM $WIRELESS_NAME $WIRELESS_STRENGTH%"
else
    echo -e "WIRED"
fi
